sample_table: "conf/private/sample_table.csv"
peptable: "conf/private/peptable.csv"

samples:
  - "PRO1"
  - "PRO2"
  - "PRO3"
  - "SEN1"
  - "SEN2"
  - "SEN3"


paralellize_bioc: 8
counttypes:
  - "featurecounts_genes"
telocaltypes:
  - "telocal_multi"
  - "telocal_uniq"
tecounttypes:
  - "telescope_multi"

library_type: PE
#for illumina truseq stranded, "2" for feature counts; "reverse" for telocal
# featureCountsstrandparam: "2"
# telocalstrandparam: "reverse"

#order matters for levels! first is the base comparator
levels:
  - "PRO"
  - "SEN"

levelsForGviz:
  - "SEN"
  - "PRO"

#mappings
levelslegendmap:
  SEN: "SEN"
  PRO: "PRO"


#analysis settings
contrasts:
  - "condition_SEN_vs_PRO"

  # - "condition_X3TC_vs_Ctrl"
  # - "condition_FTC_vs_Ctrl"
  # - "condition_CAS_vs_Ctrl"
  # - "condition_KREB_vs_Ctrl"

#note that I ommit condition_ since for most plotting applications, this helps with labelling
contrast_colors:
  condition_SEN_vs_PRO: "red"

condition_colors:
  SEN: "red"
  PRO: "blue"


genesets_for_gsea:
  msigdbH: /users/mkelsey/data/ref/genesets/human/msigdb/h.all.v2023.2.Hs.symbols.gmt
  msigdbC2_CPG: /users/mkelsey/data/ref/genesets/human/msigdb/c2.cgp.v2023.2.Hs.symbols.gmt
  msigdbC2_CP: /users/mkelsey/data/ref/genesets/human/msigdb/c2.cp.v2023.2.Hs.symbols.gmt
  msigdbC3_TFT: /users/mkelsey/data/ref/genesets/human/msigdb/c3.tft.v2023.2.Hs.symbols.gmt
  msigdbC5_GO: /users/mkelsey/data/ref/genesets/human/msigdb/c5.go.v2023.2.Hs.symbols.gmt
  msigdbC2_CPG_SENMAYO: /users/mkelsey/data/ref/genesets/human/msigdb/SAUL_SEN_MAYO.v2023.2.Hs.gmt

genesets_for_heatmaps:
  Senescence: /users/mkelsey/data/ref/genesets/human/mycustom/senescence.txt
  InflammatoryGenes: /users/mkelsey/data/ref/genesets/human/mycustom/inflammatory.txt
