annotation_genes: "/oscar/data/jsedivy/mkelsey/ref/genomes/hs1/refseq_2023_10/GCF_009914755.1_T2T-CHM13v2.0_genomic.ucscnames.gtf"
annotation_genes_bed12: "/oscar/data/jsedivy/mkelsey/ref/genomes/hs1/refseq_2023_10/GCF_009914755.1_T2T-CHM13v2.0_genomic.ucscnames.bed"
annotation_genesandrtes: "/oscar/data/jsedivy/mkelsey/ref/genomes/hs1/annotations4/hs1.repMask.refseq.sorted.gtf"
annotation_rtes: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/annotations/repeatmasker.gff2"

r_annotation_fragmentsjoined: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/annotations/repeatmasker.gtf.rformatted.fragmentsjoined.csv"
r_repeatmasker_annotation: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/annotations/repeatmasker_annotation.csv"


#genomes
reference: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/ref.fa"
starindex: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/ref_indeces/star_index"

# referencesize: "/users/mkelsey/data/ref/genomes/hs1/hs1.chrom.sizes.txt"
#indeces

telocalmapping: "/users/mkelsey/data/ref/genomes/hs1/TElocal/T2T_CHM13_v2_rmsk_TE.gtf.locInd.locations.annotated.intactnessAnn"
bowtie2hs1index: "/users/mkelsey/data/ref/genomes/hs1/hs1.sorted_bowtie2/hs1"

genelistsforplot:
  - "/users/mkelsey/data/ref/genesets/sasp.txt"
#annotations
ideogram: "/users/mkelsey/data/ref/genomes/hs1/annotations2/Ideogram.bed"
ideogram2: "/users/mkelsey/data/ref/genomes/hs1/annotations2/ideogramWithStain.bed"
repeats: "/users/mkelsey/data/ref/genomes/hs1/annotations/hs1_RepeatMasker.sorted"
repeatsbed: "/users/mkelsey/data/ref/genomes/hs1/annotations/repeatmasker.bed"
repeats2: "/users/mkelsey/data/ref/genomes/hs1/annotations2/repeatMasker.gtf"
repeats2gz: "/users/mkelsey/data/ref/genomes/hs1/annotations2/repeatMasker.copy.gtf.gz"

repeatsannotated: "/users/mkelsey/data/ref/genomes/hs1/annotations2/repeatMaskerAnnotated.bed"
l1hs6kb: "/users/mkelsey/data/ref/genomes/hs1/annotations/L1HS6kb"
aluY: "/users/mkelsey/data/ref/genomes/hs1/annotations/aluY"
HERVK: "/users/mkelsey/data/ref/genomes/hs1/annotations/HERVK"
intactl1s: "/users/mkelsey/data/ref/genomes/hs1/annotations2/subsets/l1hsintact.bed"
l1hs6kbintact: "/users/mkelsey/data/ref/genomes/hs1/annotations/L1HS6kbintact"
l1hs6kbintactbed: "/users/mkelsey/data/ref/genomes/hs1/annotations/L1HS6kbintact.bed5"
SenMayoHuman: "/users/mkelsey/data/ref/genesets/SenMayoGeneSetHuman.txt"
l1hsorf2intact: "/gpfs/data/jsedivy/mkelsey/ref/genomes/hs1/annotations/blast_repeatmasker/l1/orf2/L1_ORF2intact.bed"



  #these are for the ideogram
namedcolorlist:
  L1UP: "8c00ff"
  AluUP: "ff9d00"
  ERVKUP: "ff7be2"
  L1HSUP: "8c00ff"
  AluYUP: "ff9d00"
  HERVK-intUP: "ff7be2"
  L1DOWN: "00ff62"
  AluDOWN: "0be7e4"
  ERVKDOWN: "8c00ff"
  L1HSDOWN: "00ff62"
  AluYDOWN: "0be7e4"
  HERVK-intDOWN: "8c00ff"

namedmarkerlist:
  L1: "circle"
  Alu: "box"
  ERVK: "triange"
  L1HS: "circle"
  AluY: "box"
  HERVK-int: "triangle"

activeelementminlength:
  L1HS: 5999
  AluY: 280
  HERVK-int: 7000
  L1PA2: 5000
  L1PA3: 5000
  L1PA4: 5000
  L1PA5: 5000
  L1PA6-9: 5000

lengthreq:
  'L1': 0
  'Alu': 0
  'ERVK': 0
  'L1HS': 5999
  'AluY': 280
  'HERVK-int': 7000
  'L1PA2': 5000
  'L1PA3': 5000
  'L1PA4': 5000
  'L1PA5': 5000
  'L1PA6-9': 5000


rtestoplot:
  - "L1HS"
  - "AluY"
  - "HERVK-int"


repeatanalysis:
  'Family':
    'L1': 'L1:LINE'
    'Alu': 'Alu:SINE'
    'ERVK': 'ERVK:LTR'
  'ActiveFamily':
    'L1HS': 'L1HS'
    'AluY': 'AluY'
    'HERVK-int': 'HERVK(.)*int'
  'Subfamily':
    'L1HS': 'L1HS'
    'AluY': 'AluY'
    'HERVK-int': 'HERVK(.)*int'
    'L1PA2': 'L1PA2'
    'L1PA3': 'L1PA3'
    'L1PA4': 'L1PA4'
    'L1PA5': 'L1PA5'
    'L1PA6-9': 'L1PA[6789]{1}'

genedensity:
  L1HS: "/users/mkelsey/data/ref/genomes/hs1/annotations/hs1.L1HS.density.bed4"
  AluY: "/users/mkelsey/data/ref/genomes/hs1/annotations/hs1.HERVK.density.bed4"
  HERVK-int: "/users/mkelsey/data/ref/genomes/hs1/annotations/hs1.AluY.density.bed4"

karyotype: "/users/mkelsey/data/ref/genomes/hs1/karyotype.tsv"

L1HSconsensus: "/users/mkelsey/data/ref/sequences/L1HSconsensus.fa"
AluYconsensus: "/users/mkelsey/data/ref/sequences/AluYconsensus.fa"
HERVK-intconsensus: "/users/mkelsey/data/ref/sequences/HERVK-intconsensus.fa"
L1HSoutgroup: "/users/mkelsey/data/ref/sequences/L1HSconsensus.fa"
AluYoutgroup: "/users/mkelsey/data/ref/sequences/AluJbconsensus.fa"
HERVK-intoutgroup: "/users/mkelsey/data/ref/sequences/HERVL-intconsensus.fa"
